# Standards: 0.11
---

# 3.5.3 Ensure iptables is installed

- name: 3.5.3 - Ensure iptables is installed
  yum:
    name: "iptables"
    state: latest
  tags:
    - level-1
    - section-3
    - "3.5.3"
    - scored
 
- name: iptables-services is to be installed on amazon linux 2 for proper management of iptables
  yum:
    name: "iptables-services"
    state: latest
  tags:
    - level-1
    - section-3
    - "3.5.3"
    - scored

- name: save iptables rules         # save previously performed configuration for IPv4 rules
  command: service iptables save    # iptables-save doesnt work on amazon Linux 2
  become: true
 
- name: save ip6tables rules         # save previously performed configuration for IPv6 rules
  command: service ip6tables save    # iptables-save doesnt work on amazon Linux 2
  become: true
  
- name: Disable service iptables
  service:
    name: iptables
    enabled: no
      